# .github/workflows/aspnetcore-sonarcloud.yml

name: Build, Test, and Analyze with SonarCloud

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-test-analyze:
    name: Build, Test, and SonarCloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore SocialMediaApp.sln
      
      - name: Build
        run: dotnet build SocialMediaApp.sln --no-restore --configuration Release
      
      - name: Test with Coverage
        run: |
          dotnet test SocialMediaApp.sln --no-build --configuration Release \
            --collect:"XPlat Code Coverage" \
            --logger trx
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Generate Coverage Report
        run: |
          reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coveragereport" -reporttypes:"Cobertura"

      - name: Upload coverage to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}

